spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://localhost:8888  # Ensure the Config Server URL is correct

  datasource:
    url: jdbc:postgresql://localhost:5432/yourdb   # Replace 'yourdb' with the actual database name
    username: yourdbuser                          # Set your actual database username
    password: yourdbpassword                      # Set your actual database password
    driver-class-name: org.postgresql.Driver      # For PostgreSQL, change if you're using a different DB
    hikari:
      maximum-pool-size: 10                       # Adjust connection pool size as needed

  flyway:
    enabled: true
    locations: classpath:db/migration               # Default location for Flyway migration scripts
    baseline-on-migrate: true                        # Automatically baseline the database on first run

  logging:
    level:
      org.springframework.web: DEBUG              # Change logging level as per your requirements
      org.hibernate: ERROR

  management:
    endpoints:
      web:
        exposure:
          include: "*"                             # Expose all actuator endpoints for monitoring
    health:
      mysql:
        enabled: true
      diskspace:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/   # Eureka server URL
    instance:
      hostname: product-service-hostname            # Use dynamic hostname if necessary

---
spring:
  profiles: dev
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb    # Database for dev profile
    username: devuser
    password: devpassword

  flyway:
    locations: classpath:db/migration/dev

---
spring:
  profiles: prod
  config:
    import: optional:configserver:http://config-server:8888  # Prod config server URL
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/proddb   # Database for prod profile
    username: produser
    password: prodpassword

  flyway:
    locations: classpath:db/migration/prod


